# Site settings
title: 皮皮虾 我们走
header-img: img/home-bg.jpg
email: 425830509@qq.com
copyright_name: SimbaScorpio
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "https://SimbaScorpio.github.io"
twitter_username: Hu_Jiangchuan
github_username:  SimbaScorpio
facebook_username:  profile.php?id=100007371646912
email_username:  425830509@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
